# ==========================================
# Linux File Organizer Configuration
# ==========================================

IMAGES="jpg jpeg png gif svg ico tiff tif bmp webp heic"
DOCUMENTS="pdf doc docx txt odt xls xlsx ppt pptx"
VIDEOS="mp4 mkv avi mov wmv flv"
MUSIC="mp3 wav flac aac ogg"
ARCHIVES="zip tar gz rar 7z"
SCRIPTS="sh py js c cpp java"